### ISSUE TITLE
As a developer I want to evaluate Backend Frameworks: Node.js with Express, Python with Flask or Django, Java with Spring Boot.

### ISSUE THREAD

**Issue by dev-nikita-ctrl** [dev-nikita-ctrl/HaaS-MAVeN-BackEnd#2]
- Read documentation and tutorials.
- Compare Flask and Django for ease of use, flexibility, and scalability.

**Comment by MaheraFurniturewala** [comment]
Due to it's lightweight nature and since our project has a smaller scope we will be going ahead with Flask
